spring:
  datasource:
    url: jdbc:mysql://localhost:3306/affablebean?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: nbuser

mybatis-plus:
  mapper-locations: classpath*:com/kennen/springbootmybatis/common/dao/repository/mapping/*.xml
  type-aliases-package: com.kennen.springbootmybatis.common.dao.entity
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true 
